[package]
name = "repro-build"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "repro"
path = "src/main.rs"

[dependencies]
clap = { version = "4.5.7", features = ["derive"] }
env_logger = "0.11.3"
fuser = "0.14.0"
libc = "0.2.155"
